name: Setup
description: Set Up Job


inputs:
  commit:
    description: Commit
    required: true
  name:
    description: Status and artifacts name
    required: true
  description:
    description: Status description
    required: true
  checkout-dir:
    description: Checkout destination.  Skip checkout if empty
    default: .
  checkout-url:
    description: Checkout URL.  Skip checkout if empty
    default: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
  upload:
    description: List of files to upload as artifacts
  force:
    description: Force rerun
    default: false
  token:
    description: GitHub access token
    default: ${{ github.token }}
outputs:
  has-already-run:
    description: Has job already run?
    value: ${{ steps.main.outputs.has-already-run }}


runs:
  using: composite
  steps:

    - id: main
      uses: szatanjl/action-setup/main@main
      with:
        commit: ${{ inputs.commit }}
        name: ${{ inputs.name }}
        description: ${{ inputs.description }}
        checkout-dir: ${{ inputs.checkout-dir }}
        checkout-url: ${{ inputs.checkout-url }}
        force: ${{ inputs.force }}
        token: ${{ inputs.token }}

    - if: (!steps.main.outputs.has-already-run)
      uses: szatanjl/action-setup/on-success@main
      with:
        commit: ${{ inputs.commit }}
        name: ${{ inputs.name }}
        description: ${{ inputs.description }}
        upload: ${{ inputs.upload }}
        token: ${{ inputs.token }}

    - if: (!steps.main.outputs.has-already-run)
      uses: szatanjl/action-setup/on-failure@main
      with:
        commit: ${{ inputs.commit }}
        name: ${{ inputs.name }}
        description: ${{ inputs.description }}
        upload: ${{ inputs.upload }}
        token: ${{ inputs.token }}

    - if: (!steps.main.outputs.has-already-run)
      uses: szatanjl/action-setup/on-cancelled@main
      with:
        commit: ${{ inputs.commit }}
        name: ${{ inputs.name }}
        description: ${{ inputs.description }}
        token: ${{ inputs.token }}

    - if: (!steps.main.outputs.has-already-run) && (!success())
      uses: szatanjl/action-setup/on-error@main
      with:
        commit: ${{ inputs.commit }}
        name: ${{ inputs.name }}
        description: ${{ inputs.description }}
        token: ${{ inputs.token }}
