name: Setup
description: Set Up Job

inputs:
  commit:
    description: Commit
    required: true
  name:
    description: Status name
    required: true
  description:
    description: Status description
    required: true
  force:
    description: Force rerun
    default: false
  token:
    description: GitHub access token
    default: ${{ github.token }}
outputs:
  has-already-run:
    description: Has job already run?

runs:
  using: node20
  main: main.js
