name: Setup - success
description: Complete Job in Case of Success

inputs:
  commit:
    description: Commit
    required: true
  name:
    description: Status name
    required: true
  description:
    description: Status description
    required: true
  token:
    description: GitHub access token
    default: ${{ github.token }}

runs:
  using: node20
  main: main.js
  post-if: success()
  post: post.js
