name: Test
run-name: Test -- ${{ inputs.commit }}
permissions:
  contents: read
  statuses: write


on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit
        type: string
        required: true


jobs:

  linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: linux
          description: Test Linux
      - name: Post-setup
        run: echo 'Post-setup'

  windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Pre-setup
        shell: bash
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: windows
          description: Test Windows
      - name: Post-setup
        shell: bash
        run: echo 'Post-setup'

  macos:
    name: Test MacOS
    runs-on: macos-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: macos
          description: Test MacOS
      - name: Post-setup
        run: echo 'Post-setup'

  on-failure-after:
    name: Test When Job Fails After Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-failure-after
          description: Test When Job Fails After Setup
      - name: Post-setup
        run: false

  on-failure-before:
    name: Test When Job Fails Before Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: false
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-failure-before
          description: Test When Job Fails Before Setup
      - name: Post-setup
        run: echo 'Post-setup'

  on-cancelled-after:
    name: Test When Job Is Cancelled After Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-cancelled-after
          description: Test When Job Is Cancelled After Setup
      - name: Post-setup
        run: sleep 300

  on-cancelled-before:
    name: Test When Job Is Cancelled Before Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: sleep 300
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-cancelled-before
          description: Test When Job Is Cancelled Before Setup
      - name: Post-setup
        run: echo 'Post-setup'

  test-statuses:
    name: Test Statuses
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: test-statuses
          description: Test Statuses
      - run: sleep 30

  invalid-commit:
    name: Test Invalid Commit
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: invalid-commit
          name: test-invalid-commit
          description: Test Invalid Commit
      - name: Post-setup
        run: echo 'Post-setup'
