name: Test
run-name: Test -- ${{ inputs.commit }}
permissions:
  contents: read
  statuses: write


on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit
        type: string
        required: true


jobs:

  linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: ls -A .
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: linux
          description: Test Linux
          upload: |
            README.md
            LICENSE
      - name: Post-setup
        run: ls -A .

  windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Pre-setup
        shell: bash
        run: ls -A .
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: windows
          description: Test Windows
          upload: |
            README.md
            LICENSE
      - name: Post-setup
        shell: bash
        run: ls -A .

  macos:
    name: Test MacOS
    runs-on: macos-latest
    steps:
      - name: Pre-setup
        run: ls -A .
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: macos
          description: Test MacOS
          upload: |
            README.md
            LICENSE
      - name: Post-setup
        run: ls -A .

  on-failure-after:
    name: Test When Job Fails After Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-failure-after
          description: Test When Job Fails After Setup
          upload: |
            README.md
            LICENSE
      - name: Post-setup
        run: false

  on-failure-before:
    name: Test When Job Fails Before Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: false
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-failure-before
          description: Test When Job Fails Before Setup
          upload: |
            README.md
            LICENSE
      - name: Post-setup
        run: echo 'Post-setup'

  on-cancelled-after:
    name: Test When Job Is Cancelled After Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-cancelled-after
          description: Test When Job Is Cancelled After Setup
          upload: |
            README.md
            LICENSE
      - name: Post-setup
        run: sleep 300

  on-cancelled-before:
    name: Test When Job Is Cancelled Before Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: sleep 300
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-cancelled-before
          description: Test When Job Is Cancelled Before Setup
          upload: |
            README.md
            LICENSE
      - name: Post-setup
        run: echo 'Post-setup'

  test-statuses:
    name: Test Statuses
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: test-statuses
          description: Test Statuses
      - run: sleep 30

  test-checkout-dir:
    name: Test Checkout Dir
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: ls -A .
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: test-checkout-dir
          description: Test Checkout Dir
          checkout-dir: src
      - name: Post-setup
        run: ls -A . src

  test-no-checkout:
    name: Test Setup Without Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: ls -A .
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: test-no-checkout
          description: Test Setup Without Checkout
          checkout-dir:
      - name: Post-setup
        run: ls -A .

  test-upload:
    name: Test Upload
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: test-upload
          description: Test Upload
          checkout-dir:
          upload: |
            dir
            empty-dir
            file
            symlink
      - name: Post-setup
        run: |
          mkdir dir empty-dir
          echo file > file
          echo file > dir/file
          ln -s file symlink

  test-upload-broken-symlink:
    name: Test Upload Broken Symlink
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: test-upload-broken-symlink
          description: Test Upload Broken Symlink
          checkout-dir:
          upload: broken-symlink
      - name: Post-setup
        run: ln -s broken broken-symlink

  test-upload-missing:
    name: Test Upload Missing Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: test-upload-missing
          description: Test Upload Missing Artifacts
          checkout-dir:
          upload: |
            TEST1
            README.md
            LICENSE
            TEST2
      - name: Post-setup
        run: |
          echo TEST1 > TEST1
          echo TEST2 > TEST2

  invalid-commit:
    name: Test Invalid Commit
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: invalid-commit
          name: test-invalid-commit
          description: Test Invalid Commit
      - name: Post-setup
        run: echo 'Post-setup'

  rerun-after-success1:
    name: Test Rerun After Success 1
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - id: setup
        name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-after-success
          description: Test Rerun After Success
      - run: ls -A .
      - name: Post-setup
        if: (!steps.setup.outputs.has-already-run)
        run: echo 'Post-setup'

  rerun-after-success2:
    name: Test Rerun After Success 2
    runs-on: ubuntu-latest
    needs: rerun-after-success1
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - id: setup
        name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-after-success
          description: Test Rerun After Success
      - run: ls -A .
      - name: Post-setup
        if: (!steps.setup.outputs.has-already-run)
        run: echo 'Post-setup'

  rerun-after-failure1:
    name: Test Rerun After Failure 1
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-after-failure
          description: Test Rerun After Failure
      - run: ls -A .
      - name: Post-setup
        run: false

  rerun-after-failure2:
    name: Test Rerun After Failure 2
    runs-on: ubuntu-latest
    needs: rerun-after-failure1
    if: always()
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - id: setup
        name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-after-failure
          description: Test Rerun After Failure
      - if: always()
        run: ls -A .
      - name: Post-setup
        if: (!steps.setup.outputs.has-already-run)
        run: echo 'Post-setup'

  rerun-force1:
    name: Test Force Rerun 1
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-force
          description: Test Force Rerun
      - run: ls -A .
      - name: Post-setup
        run: echo 'Post-setup'

  rerun-force2:
    name: Test Force Rerun 2
    runs-on: ubuntu-latest
    needs: rerun-force1
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - id: setup
        name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-force
          description: Test Force Rerun
          force: true
      - run: ls -A .
      - name: Post-setup
        if: (!steps.setup.outputs.has-already-run)
        run: echo 'Post-setup'
