name: Test
run-name: Test -- ${{ inputs.commit }}
permissions:
  contents: read
  statuses: write


on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit
        type: string
        required: true


jobs:

  linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: linux
          description: Test Linux
      - name: Post-setup
        run: echo 'Post-setup'

  windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Pre-setup
        shell: bash
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: windows
          description: Test Windows
      - name: Post-setup
        shell: bash
        run: echo 'Post-setup'

  macos:
    name: Test MacOS
    runs-on: macos-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: macos
          description: Test MacOS
      - name: Post-setup
        run: echo 'Post-setup'

  on-failure-after:
    name: Test When Job Fails After Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-failure-after
          description: Test When Job Fails After Setup
      - name: Post-setup
        run: false

  on-failure-before:
    name: Test When Job Fails Before Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: false
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-failure-before
          description: Test When Job Fails Before Setup
      - name: Post-setup
        run: echo 'Post-setup'

  on-cancelled-after:
    name: Test When Job Is Cancelled After Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-cancelled-after
          description: Test When Job Is Cancelled After Setup
      - name: Post-setup
        run: sleep 300

  on-cancelled-before:
    name: Test When Job Is Cancelled Before Setup
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: sleep 300
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: on-cancelled-before
          description: Test When Job Is Cancelled Before Setup
      - name: Post-setup
        run: echo 'Post-setup'

  test-statuses:
    name: Test Statuses
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: test-statuses
          description: Test Statuses
      - run: sleep 30

  invalid-commit:
    name: Test Invalid Commit
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: invalid-commit
          name: test-invalid-commit
          description: Test Invalid Commit
      - name: Post-setup
        run: echo 'Post-setup'

  rerun-after-success1:
    name: Test Rerun After Success 1
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - id: setup
        name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-after-success
          description: Test Rerun After Success
      - name: Post-setup
        if: (!steps.setup.outputs.has-already-run)
        run: echo 'Post-setup'

  rerun-after-success2:
    name: Test Rerun After Success 2
    runs-on: ubuntu-latest
    needs: rerun-after-success1
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - id: setup
        name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-after-success
          description: Test Rerun After Success
      - name: Post-setup
        if: (!steps.setup.outputs.has-already-run)
        run: echo 'Post-setup'

  rerun-after-failure1:
    name: Test Rerun After Failure 1
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-after-failure
          description: Test Rerun After Failure
      - name: Post-setup
        run: false

  rerun-after-failure2:
    name: Test Rerun After Failure 2
    runs-on: ubuntu-latest
    needs: rerun-after-failure1
    if: always()
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - id: setup
        name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-after-failure
          description: Test Rerun After Failure
      - name: Post-setup
        if: (!steps.setup.outputs.has-already-run)
        run: echo 'Post-setup'

  rerun-force1:
    name: Test Force Rerun 1
    runs-on: ubuntu-latest
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-force
          description: Test Force Rerun
      - name: Post-setup
        run: echo 'Post-setup'

  rerun-force2:
    name: Test Force Rerun 2
    runs-on: ubuntu-latest
    needs: rerun-force1
    steps:
      - name: Pre-setup
        run: echo 'Pre-setup'
      - id: setup
        name: Setup
        uses: szatanjl/action-setup@main
        with:
          commit: ${{ inputs.commit }}
          name: rerun-force
          description: Test Force Rerun
          force: true
      - name: Post-setup
        if: (!steps.setup.outputs.has-already-run)
        run: echo 'Post-setup'
